### ISSUE TITLE
undefined method `enum_kstat' for Facter::Util::Processor:Module

### ISSUE THREAD

**Issue by pitluga** [braintree/litmus_paper#1]
Seems to happen the first time the application runs after being first installed. Found another similar example. Seems to be an autoload issue with facter. Will require more digging into the gem.

http://projects.puppetlabs.com/issues/12879

**Comment by ahayworth** [comment]
The facter dependency was removed, so this can be closed. https://github.com/braintree/litmus_paper/commit/f511a7f535a045e97678c558e3fd25126c6a9663
