### ISSUE TITLE
Signals being handled correctly on 1.9.2 + Ubuntu

### ISSUE THREAD

**Issue by pitluga** [braintree/litmus_paper#2]
Sending HUPs doesn't work.

From the post below, the work around is to send a CONT first, ie

kill -CONT `cat /path/to.pid`
kill -HUP `cat /path/to.pid`

nThe issue is with the kernel, so nothing to be address here.

http://www.ruby-forum.com/topic/1782469

**Comment by ahayworth** [comment]
The bug indicates this was fixed in `2.6.39`. Given how old that is, I'm comfortable closing this.

http://web.archive.org/web/20110811222713/https://www.ruby-forum.com/topic/1782469
