### ISSUE TITLE
Evaluate unicorn dependencies

### ISSUE THREAD

**Issue by ahayworth** [braintree/litmus_paper#29]
It's rather awkward that we couple this so tightly to unicorn, when it's otherwise a rack app that should fit in any rack-compliant server. Some thoughts:
- We could uncouple it from unicorn, and provide examples of how to start it alongside unicorn.
- We could bundle it _with_ unicorn and a portable ruby runtime, so that it can be installed with any gem/ruby environment.
- We could provide examples of how to run it in other rack-compliant webservers (Thin? Puma?).

We should discuss paths forward a bit - it's just awkward that there's only one real way to run it, and that you have to install it through rubygems.

**Comment by ssgelm** [comment]
I'm not sure how I feel here.  I agree that it is weirdly coupled to unicorn, but on the flip side the reason we moved it from thin to unicorn was because the performance was lacking, which is a concern given the nature of litmus.

**Comment by ahayworth** [comment]
That's a reasonable point.
