### ISSUE TITLE
Consider re-writing in a concurrency-friendly language

### ISSUE THREAD

**Issue by ahayworth** [braintree/litmus_paper#31]
It's been proposed that litmus_paper should be re-written in a language that's friendly to concurrency (like Go). That may open up interesting possibilities. We should evaluate this and discuss.

**Comment by ssgelm** [comment]
Yes please.  I have been working on a rewrite in go.  It would be nice to put more effort into this.

**Comment by tcsalameh** [comment]
Merging in #32 removes a big blocker for doing this, although we'd have to drop support for ruby-based configuration.

I think the main questions are:
1.) We're not using Ruby's concurrency constructs much right now, except for a bit in the agent check code. If we changed the architecture of the application to have separate health-check and responder processes, how much would this buy us? How much would it increase complexity over something equivalent written in Go? Would the effort to do this be great enough that we'd be better off doing a rewrite anyway?
2.) How much time would a rewrite take? It sounds like there's already some work in progress here.
