### ISSUE TITLE
Add ability to default port

### ISSUE THREAD

**Issue by phinze** [braintree/litmus_paper#7]
in `/etc/litmus.conf`, provide a `port` keyword

``` ruby
include_files "litmus.d/*.conf"
port 80
```

`litmus` and `litmusctl` should use this value for their default port.

**Comment by ahayworth** [comment]
This was indeed done ages ago! Hooray! https://github.com/braintree/litmus_paper/commit/6d4b869820a455b7ead3fae069a617036ee171b0
